[package]
name = "sel-validator-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
sel-common = { path = "../sel-common" }
sel-validator = { path = "../sel-validator" }
clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
