[package]
name = "sel-validator"
version = "1.1.0-alpha"
edition.workspace = true
rust-version.workspace = true

[dependencies]
sel-common = { path = "../sel-common" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
hmac.workspace = true
ed25519-dalek = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[features]
default = ["hmac"]
hmac = []
ed25519 = ["dep:ed25519-dalek", "dep:rand"]
